### ISSUE TITLE
Sitemaps not displayed at all

### ISSUE THREAD

**Issue by afflux** [ibaton/3House#116]
On 3House 5.5.1, I get empty sitemaps on my sites. Reproducible on demo.openhab.org:8080, e.g. when opening any of the rooms (e.g. Cellar). 

Unfortunately, due to proguard applied, debugging is impossible, as the exception in the logcat shows:

```
12-28 13:40:40.776 W/System.err(23403): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method treehou.se.habit.ui.b.a.c.b, parameter parent
12-28 13:40:40.776 W/System.err(23403): 	at treehou.se.habit.ui.b.a.c.b(Unknown Source)
12-28 13:40:40.776 W/System.err(23403): 	at treehou.se.habit.ui.b.a.c.j.<init>(Unknown Source)
12-28 13:40:40.776 W/System.err(23403): 	at treehou.se.habit.ui.b.a.c.j.a(Unknown Source)
12-28 13:40:40.776 W/System.err(23403): 	at treehou.se.habit.ui.b.a.c.i.a(Unknown Source)
12-28 13:40:40.776 W/System.err(23403): 	at treehou.se.habit.ui.b.b.a(Unknown Source)
12-28 13:40:40.776 W/System.err(23403): 	at treehou.se.habit.ui.sitemaps.page.d.a(Unknown Source)
12-28 13:40:40.776 W/System.err(23403): 	at treehou.se.habit.ui.sitemaps.page.d.a(Unknown Source)
12-28 13:40:40.776 W/System.err(23403): 	at treehou.se.habit.ui.sitemaps.page.d.a(Unknown Source)
12-28 13:40:40.776 W/System.err(23403): 	at treehou.se.habit.ui.sitemaps.page.d.a(Unknown Source)
12-28 13:40:40.776 W/System.err(23403): 	at treehou.se.habit.ui.sitemaps.page.h.a(Unknown Source)
12-28 13:40:40.776 W/System.err(23403): 	at io.a.e.d.g.a_(Unknown Source)
12-28 13:40:40.776 W/System.err(23403): 	at io.a.e.e.d.ax.run(Unknown Source)
12-28 13:40:40.776 W/System.err(23403): 	at io.a.a.b.f.run(Unknown Source)
12-28 13:40:40.776 W/System.err(23403): 	at android.os.Handler.handleCallback(Handler.java:751)
12-28 13:40:40.776 W/System.err(23403): 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-28 13:40:40.776 W/System.err(23403): 	at android.os.Looper.loop(Looper.java:154)
12-28 13:40:40.776 W/System.err(23403): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
12-28 13:40:40.776 W/System.err(23403): 	at java.lang.reflect.Method.invoke(Native Method)
12-28 13:40:40.777 W/System.err(23403): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-28 13:40:40.777 W/System.err(23403): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by afflux** [comment]
Appears to be solved in 5.5.2

**Comment by ibaton** [comment]
@afflux Thanks for the update.
I made a fix, but I wasn't sure that it would fix the problem.

**Comment by afflux** [comment]
I'm reopening this issue, as I believe the root cause persists: I'm now seeing the same exception on pages with sliders, and the sliders are not rendered (thankfully without obfuscated backtrace):

```
01-29 20:59:42.744 W/System.err(29249): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter parent
01-29 20:59:42.744 W/System.err(29249): 	at treehou.se.habit.ui.widgets.factories.SliderWidgetFactory.build(SliderWidgetFactory.kt)
01-29 20:59:42.744 W/System.err(29249): 	at treehou.se.habit.ui.widgets.WidgetFactory.createWidget(WidgetFactory.java:57)
01-29 20:59:42.744 W/System.err(29249): 	at treehou.se.habit.ui.sitemaps.page.PagePresenter.invalidateWidgets(PagePresenter.kt:216)
01-29 20:59:42.744 W/System.err(29249): 	at treehou.se.habit.ui.sitemaps.page.PagePresenter.updatePage(PagePresenter.kt:143)
01-29 20:59:42.745 W/System.err(29249): 	at treehou.se.habit.ui.sitemaps.page.PagePresenter.updatePage(PagePresenter.kt:158)
01-29 20:59:42.745 W/System.err(29249): 	at treehou.se.habit.ui.sitemaps.page.PagePresenter.access$updatePage(PagePresenter.kt:28)
01-29 20:59:42.745 W/System.err(29249): 	at treehou.se.habit.ui.sitemaps.page.PagePresenter$requestPageUpdate$1.accept(PagePresenter.kt:106)
01-29 20:59:42.745 W/System.err(29249): 	at treehou.se.habit.ui.sitemaps.page.PagePresenter$requestPageUpdate$1.accept(PagePresenter.kt:28)
01-29 20:59:42.745 W/System.err(29249): 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
01-29 20:59:42.745 W/System.err(29249): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
01-29 20:59:42.745 W/System.err(29249): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
01-29 20:59:42.745 W/System.err(29249): 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
01-29 20:59:42.745 W/System.err(29249): 	at android.os.Handler.handleCallback(Handler.java:751)
01-29 20:59:42.745 W/System.err(29249): 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-29 20:59:42.745 W/System.err(29249): 	at android.os.Looper.loop(Looper.java:154)
01-29 20:59:42.745 W/System.err(29249): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
01-29 20:59:42.745 W/System.err(29249): 	at java.lang.reflect.Method.invoke(Native Method)
01-29 20:59:42.745 W/System.err(29249): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
01-29 20:59:42.745 W/System.err(29249): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

The issue does not occur on this page: http://demo.openhab.org:8080/basicui/app?w=0202&sitemap=demo

But it does occur on this one: http://demo.openhab.org:8080/basicui/app?w=GF_Living&sitemap=demo

I believe this could be fixed by making parent nullable in [build()](https://github.com/ibaton/3House/blob/develop/mobile/src/main/java/treehou/se/habit/ui/widgets/factories/SliderWidgetFactory.kt#L24) and [the constructor](https://github.com/ibaton/3House/blob/develop/mobile/src/main/java/treehou/se/habit/ui/widgets/factories/SliderWidgetFactory.kt#L28).

**Comment by ibaton** [comment]
Thanks @afflux, you are correct, Releasing a new build today if it passes the tests.
