### ISSUE TITLE
Completely unusable because of crash on start-up

### ISSUE THREAD

**Issue by Flole998** [ibaton/3House#119]
If i am not mistaken, this is the issue that is causing the problem:

03-02 23:38:42.142 E/MemorizingTrustManager(5254): java.io.FileNotFoundException: /data/user/0/treehou.se.habit/app_private/KeyStore.bks (No such file or directory)

The app is trying to load the keystore but fails because it doesn't exist yet on initial startup.

**Comment by ibaton** [comment]
That is probably not the bug that crashes the app. Do you get any other types of exceptions?
It would also be good to know what kind of phone you have.

Have you tried to uninstall and the install the app again?

**Comment by Flole998** [comment]
Yes i tried reinstalling. No other exceptions. I am using a OnePlus 3 with Android oreo. The error is in connectionfactory.java:34, thats the earlierst thing referring to 3house as far as I can see

**Comment by Flole998** [comment]
Today I found this in the logcat, not sure if that's related:


java.lang.IllegalStateException: Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.
	at io.realm.BaseRealm.checkIfValid(BaseRealm.java:426)
	at io.realm.BaseRealm.removeListener(BaseRealm.java:218)
	at io.realm.Realm.removeChangeListener(Realm.java:1364)
	at io.realm.rx.RealmObservableFactory$4$2.run(RealmObservableFactory.java:103)
	at io.reactivex.disposables.RunnableDisposable.onDisposed(RunnableDisposable.java:30)
	at io.reactivex.disposables.RunnableDisposable.onDisposed(RunnableDisposable.java:20)
	at io.reactivex.disposables.ReferenceDisposable.dispose(ReferenceDisposable.java:43)
	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
	at io.reactivex.internal.disposables.SequentialDisposable.dispose(SequentialDisposable.java:73)
	at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.cancel(FlowableCreate.java:297)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.cancel(BasicFuseableSubscriber.java:158)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.dispose(ObservableFromPublisher.java:70)
	at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.disposeAll(ObservableFlatMap.java:503)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.dispose(ObservableFlatMap.java:307)
	at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.disposeAll(ObservableFlatMap.java:503)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.dispose(ObservableFlatMap.java:307)
	at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
	at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
	at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
	at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
	at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
	at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
	at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
	at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
	at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
	at io.reactivex.internal.operators.observable.ObservableCombineLatest$CombinerObserver.dispose(ObservableCombineLatest.java:331)
	at io.reactivex.internal.operators.observable.ObservableCombineLatest$LatestCoordinator.cancelSources(ObservableCombineLatest.java:146)
	at io.reactivex.internal.operators.observable.ObservableCombineLatest$LatestCoordinator.cancel(ObservableCombineLatest.java:141)
	at io.reactivex.internal.operators.observable.ObservableCombineLatest$LatestCoordinator.checkTerminated(ObservableCombineLatest.java:277)
	at io.reactivex.internal.operators.observable.ObservableCombineLatest$LatestCoordinator.drain(ObservableCombineLatest.java:213)
	at io.reactivex.internal.operators.observable.ObservableCombineLatest$LatestCoordinator.combine(ObservableCombineLatest.java:199)
	at io.reactivex.internal.operators.observable.ObservableCombineLatest$CombinerObserver.onError(ObservableCombineLatest.java:322)
	at hu.akarnokd.rxjava2.debug.ObservableOnAssembly$OnAssemblyObserver.onError(ObservableOnAssembly.java:60)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onError(ObservableSubscribeOn.java:63)

	at hu.akarnokd.rxjava2.debug.ObservableOnAssembly$OnAssemblyObserver.onError(ObservableOnAssembly.java:60)
	at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:46)
	at io.reactivex.Observable.subscribe(Observable.java:10903)
	at hu.akarnokd.rxjava2.debug.ObservableOnAssemblyCallable.subscribeActual(ObservableOnAssemblyCallable.java:43)
	at io.reactivex.Observable.subscribe(Observable.java:10903)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

**Comment by Flole998** [comment]
This is still an issue.

**Comment by Flole998** [comment]
It got fixed meanwhile.
